import { sql } from "@/lib/db";import { PlanPriceEditor } from "@/components/AdminEditors";
import {StripePriceSync} from "@/components/StripePriceSync";
import { SimplePlanEditor } from "@/components/SimplePlanEditor";
export default async function PlansAdmin(){
  const rows=await sql.unsafe("SELECT slug,display_name,monthly_price_minor,annual_price_minor,annual_discount_bps,billing_currency,supported_billing_currencies,max_active_strategies,trial_days,visible,archived,entitlements,description,available_strategy_keys,sort_order,stripe_monthly_price_id,stripe_annual_price_id FROM plans ORDER BY sort_order");
  const definitions=await sql.unsafe("SELECT key,name,enabled FROM strategy_definitions ORDER BY name");
  const prices=await sql.unsafe("SELECT p.slug,pp.currency,pp.cadence,pp.amount_minor,pp.stripe_price_id,pp.apple_product_id,pp.google_product_id,pp.active FROM plan_prices pp JOIN plans p ON p.id=pp.plan_id ORDER BY p.sort_order,pp.currency,pp.cadence");
  return <><div className="page-title"><div><div className="eyebrow">Admin · Plans</div><h1>Entitlements & pricing</h1><p>Plan access and per-currency Stripe prices are server-side configuration.</p></div></div><div className="table-wrap" tabIndex={0} role="region" aria-label="Scrollable table"><table><thead><tr><th>Plan</th><th>Monthly default</th><th>Annual default</th><th>Annual discount</th><th>Strategies</th><th>Trial</th><th>Visible</th></tr></thead><tbody>{rows.map((p:any)=><tr key={p.slug}><td>{p.display_name}</td><td>{p.billing_currency} {(Number(p.monthly_price_minor)/100).toFixed(2)}</td><td>{p.billing_currency} {(Number(p.annual_price_minor)/100).toFixed(2)}</td><td>{(Number(p.annual_discount_bps)/100).toFixed(2)}%</td><td>{p.max_active_strategies??"Unlimited"}</td><td>{p.trial_days}d</td><td>{p.visible&&!p.archived?"Yes":"No"}</td></tr>)}</tbody></table></div>
  <div className="table-wrap" tabIndex={0} role="region" aria-label="Scrollable table" style={{marginTop:16}}><table><thead><tr><th>Plan</th><th>Currency</th><th>Cadence</th><th>Amount</th><th>Stripe price</th><th>App Store</th><th>Google Play</th><th>Active</th><th>Stripe setup</th></tr></thead><tbody>{prices.map((p:any)=><tr key={p.slug+p.currency+p.cadence}><td>{p.slug}</td><td>{p.currency}</td><td>{p.cadence}</td><td>{(Number(p.amount_minor)/100).toFixed(2)}</td><td>{p.stripe_price_id??"Not configured"}</td><td>{p.apple_product_id??"-"}</td><td>{p.google_product_id??"-"}</td><td>{p.active?"Yes":"No"}</td><td><StripePriceSync slug={String(p.slug)} currency={String(p.currency)} cadence={String(p.cadence)} active={Boolean(p.active)} amountMinor={Number(p.amount_minor)}/></td></tr>)}</tbody></table></div>
  <div className="detail-grid"><SimplePlanEditor initialPlans={rows.map((p:any)=>({slug:String(p.slug),displayName:String(p.display_name),description:String(p.description??""),monthlyPriceMinor:Number(p.monthly_price_minor),annualPriceMinor:Number(p.annual_price_minor),annualDiscountBps:Number(p.annual_discount_bps),currency:String(p.billing_currency),supportedBillingCurrencies:Array.isArray(p.supported_billing_currencies)?p.supported_billing_currencies.map(String):["GBP"],maxActiveStrategies:p.max_active_strategies==null?null:Number(p.max_active_strategies),availableStrategyKeys:Array.isArray(p.available_strategy_keys)?p.available_strategy_keys.map(String):[],stripeMonthlyPriceId:p.stripe_monthly_price_id??null,stripeAnnualPriceId:p.stripe_annual_price_id??null,entitlements:p.entitlements??{},trialDays:Number(p.trial_days),visible:Boolean(p.visible),archived:Boolean(p.archived),sortOrder:Number(p.sort_order)}))} strategies={definitions.map((d:any)=>({key:String(d.key),name:String(d.name),enabled:Boolean(d.enabled)}))}/><PlanPriceEditor/></div></>;
}
